DATA_SECTION_START_BYTE =		58
IDLE_BATCHES_PER_PACKET	=		7
ATTITUDE_BATCHES_PER_PACKET	=	5
FLASHBURST_BATCHES_PER_PACKET =	7
FLASHCMP_BATCHES_PER_PACKET	=	6
LOWPOWER_BATCHES_PER_PACKET	=	5

A_TEMP_M =					(65/2)
A_TEMP_B =					0
A_LED_SNS_M =				650
A_LED_SNS_B =				0
A_LF_SNS_M =				(316/7)
A_LF_SNS_B =				-960
A_LF_OSNS_M =				(650/9)
A_LF_OSNS_B =				0
A_LF_VOLT_M =				(130/9)
A_LF_VOLT_B =				0
A_L_SNS_M =					20
A_L_SNS_B =					150
A_L_VOLT_M =				(130/9)
A_L_VOLT_B =				0
A_LREF_M =					(130/9)
A_LREF_B =					0
A_PANELREF_M =				(13/2)
A_PANELREF_B =				0
A_IR_AMB_M =				(63/8)
A_IR_AMB_B =				-11657
A_GYRO_M =					1
A_GYRO_B =					32750
A_ACCEL_M =					1
A_ACCEL_B =					32768
A_MAG_M =					(58/5)
A_MAG_B =					2800
A_RAD_TEMP_M =				(65/4)
A_RAD_TEMP_B =				2000
A_IMU_TEMP_M =				(14/9)
A_IMU_TEMP_B =				20374

class Signals:
	S_IR_OBJ, S_IR_AMB, S_PD, S_LED_TEMP_REG, S_LED_TEMP_FLASH, S_LED_SNS, S_LED_SNS_REG, S_LED_SNS_FLASH, S_LED_SNS_FLASH_BATCH, S_LF_TEMP, S_LF_SNS_REG, S_LF_SNS_FLASH, S_LF_SNS_FLASH_BATCH, S_LF_OSNS_REG, S_LF_OSNS_FLASH, S_LF_OSNS_FLASH_BATCH, S_LF_VOLT, S_L_TEMP, S_L_SNS, S_L_SNS_OFF, S_L_SNS_IDLE_RAD_OFF, S_L_SNS_IDLE_RAD_ON, S_L_SNS_TRANSMIT, S_L_SNS_IDLE_TRANS_TRANSITION, S_L_SNS_OFF_IDLE_TRANSITION, S_L_SNS_ANT_DEPLOY, S_L_VOLT, S_LREF, S_PANELREF, S_GYRO, S_ACCEL, S_MAG, S_RAD_TEMP, S_IMU_TEMP, S_3V3_REF, S_3V6_REF_OFF, S_3V6_REF_ON, S_3V6_SNS_OFF, S_3V6_SNS_ON, S_3V6_SNS_TRANSMIT, S_3V6_SNS_OFF_IDLE_TRANSITION, S_3V6_SNS_IDLE_TRANS_TRANSITION, S_5VREF_ON, S_5VREF_OFF, S_5VREF_TRANSITION = range(45)
class ELOCs:
	ELOC_NO_ERROR, ELOC_IR_POS_Y, ELOC_IR_NEG_X, ELOC_IR_NEG_Y, ELOC_IR_POS_X, ELOC_IR_NEG_Z, ELOC_IR_POS_Z, ELOC_PD_POS_Y, ELOC_PD_NEG_X, ELOC_PD_NEG_Y, ELOC_PD_POS_X, ELOC_PD_NEG_Z, ELOC_PD_POS_Z, ELOC_TEMP_LF_1, ELOC_TEMP_LF_2, ELOC_TEMP_L_1, ELOC_TEMP_L_2, ELOC_TEMP_LED_1, ELOC_TEMP_LED_2, ELOC_TEMP_LED_3, ELOC_TEMP_LED_4,	ELOC_RADIO_TEMP, ELOC_IMU_ACC, ELOC_IMU_GYRO, ELOC_IMU_MAG, ELOC_LED1SNS, ELOC_LED2SNS, ELOC_LED3SNS, ELOC_LED4SNS, ELOC_LFB1OSNS, ELOC_LFB1SNS, ELOC_LFB2OSNS, ELOC_LFB2SNS, ELOC_LF1REF, ELOC_LF2REF, ELOC_LF3REF, ELOC_LF4REF, ELOC_L1_REF, ELOC_L2_REF, ELOC_RADIO, ELOC_AD7991_BBRD, ELOC_AD7991_BBRD_L2_SNS, ELOC_AD7991_BBRD_L1_SNS, ELOC_AD7991_BBRD_L_REF, ELOC_AD7991_BBRD_PANEL_REF, ELOC_AD7991_CBRD, ELOC_AD7991_CBRD_3V6_REF, ELOC_AD7991_CBRD_3V6_SNS, ELOC_AD7991_CBRD_5V_REF, ELOC_AD7991_CBRD_3V3_REF, ELOC_TCA, ELOC_CACHED_PERSISTENT_STATE, ELOC_MRAM1_READ, ELOC_MRAM2_READ, ELOC_MRAM_READ, ELOC_MRAM1_WRITE, ELOC_MRAM2_WRITE, ELOC_MRAM_WRITE, ELOC_5V_REF, ELOC_STATE_HANDLING, ELOC_BAT_CHARGING, ELOC_ANTENNA_DEPLOY, ELOC_WATCHDOG, ELOC_IMU_TEMP, ELOC_VERIFY_REGS, ELOC_IDLE_DATA, ELOC_ATTITUDE_DATA, ELOC_FLASH, ELOC_LOW_POWER_DATA, ELOC_EQUISTACK_GET, ELOC_EQUISTACK_PUT, ELOC_BOOTLOADER, ELOC_RTOS, ELOC_BAT_L1, ELOC_BAT_L2, ELOC_BAT_LFB1, ELOC_BAT_LFB2, ELOC_BAT_CHARGING_SWITCH_1, ELOC_BAT_CHARGING_SWITCH_2, ELOC_BAT_CHARGING_SWITCH_3, ELOC_BAT_CHARGING_SWITCH_4, ELOC_BAT_CHARGING_SWITCH_5, ELOC_BAT_CHARGING_SWITCH_6, ELOC_BAT_CHARGING_SWITCH_7, ELOC_BAT_CHARGING_SWITCH_8, ELOC_BAT_CHARGING_SWITCH_9, ELOC_IR_POW, ELOC_RADIO_UPLINK, ELOC_RADIO_TRANSMIT, ELOC_RADIO_POWER, ELOC_IMU_INIT, ELOC_IMU_GYRO_INIT, ELOC_IMU_ACCEL_INIT, ELOC_IMU_MAG_INIT, ELOC_SCALING_M, ELOC_SCALING_B = range(96)
class ECODEs:
	ECODE_OK, ECODE_VALID_DATA, ECODE_NO_CHANGE, ECODE_ABORTED, ECODE_BUSY, ECODE_SUSPEND, ECODE_IO, ECODE_REQ_FLUSHED, ECODE_TIMEOUT, ECODE_BAD_DATA, ECODE_NOT_FOUND, ECODE_UNSUPPORTED_DEV, ECODE_NO_MEMORY, ECODE_INVALID_ARG, ECODE_BAD_ADDRESS, ECODE_BAD_FORMAT, ECODE_BAD_FRQ, ECODE_DENIED, ECODE_ALREADY_INITIALIZED, ECODE_OVERFLOW, ECODE_NOT_INITIALIZED, ECODE_SAMPLERATE_UNAVAILABLE, ECODE_RESOLUTION_UNAVAILABLE, ECODE_BAUDRATE_UNAVAILABLE, ECODE_PACKET_COLLISION, ECODE_PROTOCOL, ECODE_PIN_MUX_INVALID, ECODE_READING_HIGH, ECODE_READING_LOW, ECODE_OUT_OF_BOUNDS, ECODE_SIGNAL_LOST, ECODE_CONFIRM_TIMEOUT, ECODE_INCONSISTENT_DATA, ECODE_UNEXPECTED_CASE, ECODE_WATCHDOG_EARLY_WARNING, ECODE_WATCHDOG_RESET, ECODE_WATCHDOG_DID_KICK, ECODE_EXCESSIVE_SUSPENSION, ECODE_CRIT_ACTION_MUTEX_TIMEOUT, ECODE_I2C_IRPOW_MUTEX_TIMEOUT, ECODE_PROC_ADC_MUTEX_TIMEOUT, ECODE_HW_STATE_MUTEX_TIMEOUT, ECODE_USART_MUTEX_TIMEOUT, ECODE_SPI_MUTEX_TIMEOUT, ECODE_BAT_CHARGING_MUTEX_TIMEOUT, ECODE_WATCHDOG_MUTEX_TIMEOUT, ECODE_EQUISTACK_MUTEX_TIMEOUT, ECODE_ALL_MUTEX_TIMEOUT, ECODE_REWROTE_PROG_MEM, ECODE_STACK_OVERFLOW, ECODE_DET_ALREADY_HIGH, ECODE_BAT_NOT_DISCHARGING, ECODE_BAT_NOT_NOT_DISCHARGING, ECODE_BAT_NOT_CHARGING, ECODE_BAT_NOT_NOT_CHARGING, ECODE_BAT_NOT_DISCHARGING_RESTART, ECODE_BAT_FAULT, ECODE_BAT_NOT_FULL_FOR_WHILE, ECODE_BAT_LOW_VOLTAGE_FOR_WHILE, ECODE_RECOMMISSION, ECODE_ALL_SAME_VAL, ECODE_CORRUPTED, ECODE_CORRUPTED_FATAL, ECODE_INVALID_STATE_CHANGE, ECODE_TIMESTAMP_WRAPAROUND, ECODE_INCONSISTENT_STATE, ECODE_PWM_CUR_LOW_ON_DEPLOY, ECODE_PWM_CUR_LOW_ON_MAX_CYCLE, ECODE_PWM_CUR_VERY_LOW_ON_DEPLOY, ECODE_PWM_CUR_VERY_LOW_ON_MAX_CYCLE, ECODE_SOFTWARE_RESET, ECODE_SAT_RESET, ECODE_BAT_LI_TIMEOUT, ECODE_BAT_LF_TIMEOUT, ECODE_IR_POW_IN_USE_ON_STATE_CHANGE, ECODE_UPLINK_REBOOT, ECODE_UPLINK_KILL3DAYS, ECODE_UPLINK_KILL1WEEK, ECODE_UPLINK_KILLFOREVER, ECODE_UPLINK_REVIVED, ECODE_P1_NOT_DEPLOYED, ECODE_P2_NOT_DEPLOYED, ECODE_P3_NOT_DEPLOYED, ECODE_IRPOW_SEM_TOO_MANY_USERS, ECODE_IRPOW_SEM_TOO_FEW_USERS, ECODE_I2C_BUS_ERROR, ECODE_BAT_LF_CELLS_UNBALANCED, ECODE_VALID_STATE_CHANGE = range(88)

def get_line_m_from_signal(sig):
	return {
		Signals.S_IR_AMB:
			A_IR_AMB_M,
		Signals.S_LED_TEMP_REG:
			A_TEMP_M,
		Signals.S_LED_TEMP_FLASH:
			A_TEMP_M,
		Signals.S_LED_SNS:
			A_LED_SNS_M,
		Signals.S_LED_SNS_REG:
			A_LED_SNS_M,
		Signals.S_LED_SNS_FLASH:
			A_LED_SNS_M,
		Signals.S_LED_SNS_FLASH_BATCH:
			A_LED_SNS_M,
		Signals.S_L_TEMP:
			A_TEMP_M,
		Signals.S_LF_TEMP:
			A_TEMP_M,
		Signals.S_LF_SNS_REG:
			A_LF_SNS_M,
		Signals.S_LF_SNS_FLASH:
			A_LF_SNS_M,
		Signals.S_LF_SNS_FLASH_BATCH:
			A_LF_SNS_M,
		Signals.S_L_SNS:
			A_L_SNS_M,
		Signals.S_L_SNS_IDLE_RAD_OFF:
			A_L_SNS_M,
		Signals.S_L_SNS_IDLE_RAD_ON:
			A_L_SNS_M,
		Signals.S_L_SNS_TRANSMIT:
			A_L_SNS_M,
		Signals.S_L_SNS_ANT_DEPLOY:
			A_L_SNS_M,
		Signals.S_LF_VOLT:
			A_LF_VOLT_M,
		Signals.S_LF_OSNS_FLASH:
			A_LF_OSNS_M,
		Signals.S_LF_OSNS_FLASH_BATCH:
			A_LF_OSNS_M,
		Signals.S_LF_OSNS_REG:
			A_LF_OSNS_M,
		Signals.S_L_VOLT:
			A_L_VOLT_M,
		Signals.S_LREF:
			A_LREF_M,
		Signals.S_PANELREF:
			A_PANELREF_M,
		Signals.S_GYRO:
			A_GYRO_M,
		Signals.S_ACCEL:
			A_ACCEL_M,
		Signals.S_MAG:
			A_MAG_M,
		Signals.S_RAD_TEMP:
			A_RAD_TEMP_M,
		Signals.S_IMU_TEMP:
			A_IMU_TEMP_M,
	}[sig]

def get_line_b_from_signal(sig):
	return {
		Signals.S_IR_AMB:
			A_IR_AMB_B,
		Signals.S_LED_TEMP_REG:
			A_TEMP_B,
		Signals.S_LED_TEMP_FLASH:
			A_TEMP_B,
		Signals.S_LED_SNS:
			A_LED_SNS_B,
		Signals.S_LED_SNS_REG:
			A_LED_SNS_B,
		Signals.S_LED_SNS_FLASH:
			A_LED_SNS_B,
		Signals.S_LED_SNS_FLASH_BATCH:
			A_LED_SNS_B,
		Signals.S_L_TEMP:
			A_TEMP_B,
		Signals.S_LF_TEMP:
			A_TEMP_B,
		Signals.S_LF_SNS_REG:
			A_LF_SNS_B,
		Signals.S_LF_SNS_FLASH:
			A_LF_SNS_B,
		Signals.S_LF_SNS_FLASH_BATCH:
			A_LF_SNS_B,
		Signals.S_L_SNS:
			A_L_SNS_B,
		Signals.S_L_SNS_IDLE_RAD_OFF:
			A_L_SNS_B,
		Signals.S_L_SNS_IDLE_RAD_ON:
			A_L_SNS_B,
		Signals.S_L_SNS_TRANSMIT:
			A_L_SNS_B,
		Signals.S_L_SNS_ANT_DEPLOY:
			A_L_SNS_B,
		Signals.S_LF_VOLT:
			A_LF_VOLT_B,
		Signals.S_LF_OSNS_FLASH:
			A_LF_OSNS_B,
		Signals.S_LF_OSNS_FLASH_BATCH:
			A_LF_OSNS_B,
		Signals.S_LF_OSNS_REG:
			A_LF_OSNS_B,
		Signals.S_L_VOLT:
			A_L_VOLT_B,
		Signals.S_LREF:
			A_LREF_B,
		Signals.S_PANELREF:
			A_PANELREF_B,
		Signals.S_GYRO:
			A_GYRO_B,
		Signals.S_ACCEL:
			A_ACCEL_B,
		Signals.S_MAG:
			A_MAG_B,
		Signals.S_RAD_TEMP:
			A_RAD_TEMP_B,
		Signals.S_IMU_TEMP:
			A_IMU_TEMP_B,
	}[sig]

def get_ELOC_name(eloc):
	return {
		ELOCs.ELOC_NO_ERROR:
			'ELOC_NO_ERROR',
		ELOCs.ELOC_IR_POS_Y:
			'ELOC_IR_POS_Y',
		ELOCs.ELOC_IR_NEG_X:
			'ELOC_IR_NEG_X',
		ELOCs.ELOC_IR_NEG_Y:
			'ELOC_IR_NEG_Y',
		ELOCs.ELOC_IR_POS_X:
			'ELOC_IR_POS_X',
		ELOCs.ELOC_IR_NEG_Z:
			'ELOC_IR_NEG_Z',
		ELOCs.ELOC_IR_POS_Z:
			'ELOC_IR_POS_Z',
		ELOCs.ELOC_PD_POS_Y:
			'ELOC_PD_POS_Y',
		ELOCs.ELOC_PD_NEG_X:
			'ELOC_PD_NEG_X',
		ELOCs.ELOC_PD_NEG_Y:
			'ELOC_PD_NEG_Y',
		ELOCs.ELOC_PD_POS_X:
			'ELOC_PD_POS_X',
		ELOCs.ELOC_PD_NEG_Z:
			'ELOC_PD_NEG_Z',
		ELOCs.ELOC_PD_POS_Z:
			'ELOC_PD_POS_Z',
		ELOCs.ELOC_TEMP_LF_1:
			'ELOC_TEMP_LF_1',
		ELOCs.ELOC_TEMP_LF_2:
			'ELOC_TEMP_LF_2',
		ELOCs.ELOC_TEMP_L_1:
			'ELOC_TEMP_L_1',
		ELOCs.ELOC_TEMP_L_2:
			'ELOC_TEMP_L_2',
		ELOCs.ELOC_TEMP_LED_1:
			'ELOC_TEMP_LED_1',
		ELOCs.ELOC_TEMP_LED_2:
			'ELOC_TEMP_LED_2',
		ELOCs.ELOC_TEMP_LED_3:
			'ELOC_TEMP_LED_3',
		ELOCs.ELOC_TEMP_LED_4:
			'ELOC_TEMP_LED_4',
		ELOCs.ELOC_RADIO_TEMP:
			'ELOC_RADIO_TEMP',
		ELOCs.ELOC_IMU_ACC:
			'ELOC_IMU_ACC',
		ELOCs.ELOC_IMU_GYRO:
			'ELOC_IMU_GYRO',
		ELOCs.ELOC_IMU_MAG:
			'ELOC_IMU_MAG',
		ELOCs.ELOC_LED1SNS:
			'ELOC_LED1SNS',
		ELOCs.ELOC_LED2SNS:
			'ELOC_LED2SNS',
		ELOCs.ELOC_LED3SNS:
			'ELOC_LED3SNS',
		ELOCs.ELOC_LED4SNS:
			'ELOC_LED4SNS',
		ELOCs.ELOC_LFB1OSNS:
			'ELOC_LFB1OSNS',
		ELOCs.ELOC_LFB1SNS:
			'ELOC_LFB1SNS',
		ELOCs.ELOC_LFB2OSNS:
			'ELOC_LFB2OSNS',
		ELOCs.ELOC_LFB2SNS:
			'ELOC_LFB2SNS',
		ELOCs.ELOC_LF1REF:
			'ELOC_LF1REF',
		ELOCs.ELOC_LF2REF:
			'ELOC_LF2REF',
		ELOCs.ELOC_LF3REF:
			'ELOC_LF3REF',
		ELOCs.ELOC_LF4REF:
			'ELOC_LF4REF',
		ELOCs.ELOC_L1_REF:
			'ELOC_L1_REF',
		ELOCs.ELOC_L2_REF:
			'ELOC_L2_REF',
		ELOCs.ELOC_RADIO:
			'ELOC_RADIO',
		ELOCs.ELOC_AD7991_BBRD:
			'ELOC_AD7991_BBRD',
		ELOCs.ELOC_AD7991_BBRD_L2_SNS:
			'ELOC_AD7991_BBRD_L2_SNS',
		ELOCs.ELOC_AD7991_BBRD_L1_SNS:
			'ELOC_AD7991_BBRD_L1_SNS',
		ELOCs.ELOC_AD7991_BBRD_L_REF:
			'ELOC_AD7991_BBRD_L_REF',
		ELOCs.ELOC_AD7991_BBRD_PANEL_REF:
			'ELOC_AD7991_BBRD_PANEL_REF',
		ELOCs.ELOC_AD7991_CBRD:
			'ELOC_AD7991_CBRD',
		ELOCs.ELOC_AD7991_CBRD_3V6_REF:
			'ELOC_AD7991_CBRD_3V6_REF',
		ELOCs.ELOC_AD7991_CBRD_3V6_SNS:
			'ELOC_AD7991_CBRD_3V6_SNS',
		ELOCs.ELOC_AD7991_CBRD_5V_REF:
			'ELOC_AD7991_CBRD_5V_REF',
		ELOCs.ELOC_AD7991_CBRD_3V3_REF:
			'ELOC_AD7991_CBRD_3V3_REF',
		ELOCs.ELOC_TCA:
			'ELOC_TCA',
		ELOCs.ELOC_CACHED_PERSISTENT_STATE:
			'ELOC_CACHED_PERSISTENT_STATE',
		ELOCs.ELOC_MRAM1_READ:
			'ELOC_MRAM1_READ',
		ELOCs.ELOC_MRAM2_READ:
			'ELOC_MRAM2_READ',
		ELOCs.ELOC_MRAM_READ:
			'ELOC_MRAM_READ',
		ELOCs.ELOC_MRAM1_WRITE:
			'ELOC_MRAM1_WRITE',
		ELOCs.ELOC_MRAM2_WRITE:
			'ELOC_MRAM2_WRITE',
		ELOCs.ELOC_MRAM_WRITE:
			'ELOC_MRAM_WRITE',
		ELOCs.ELOC_5V_REF:
			'ELOC_5V_REF',
		ELOCs.ELOC_STATE_HANDLING:
			'ELOC_STATE_HANDLING',
		ELOCs.ELOC_BAT_CHARGING:
			'ELOC_BAT_CHARGING',
		ELOCs.ELOC_ANTENNA_DEPLOY:
			'ELOC_ANTENNA_DEPLOY',
		ELOCs.ELOC_WATCHDOG:
			'ELOC_WATCHDOG',
		ELOCs.ELOC_IMU_TEMP:
			'ELOC_IMU_TEMP',
		ELOCs.ELOC_VERIFY_REGS:
			'ELOC_VERIFY_REGS',
		ELOCs.ELOC_IDLE_DATA:
			'ELOC_IDLE_DATA',
		ELOCs.ELOC_ATTITUDE_DATA:
			'ELOC_ATTITUDE_DATA',
		ELOCs.ELOC_FLASH:
			'ELOC_FLASH',
		ELOCs.ELOC_LOW_POWER_DATA:
			'ELOC_LOW_POWER_DATA',
		ELOCs.ELOC_EQUISTACK_GET:
			'ELOC_EQUISTACK_GET',
		ELOCs.ELOC_EQUISTACK_PUT:
			'ELOC_EQUISTACK_PUT',
		ELOCs.ELOC_BOOTLOADER:
			'ELOC_BOOTLOADER',
		ELOCs.ELOC_RTOS:
			'ELOC_RTOS',
		ELOCs.ELOC_BAT_L1:
			'ELOC_BAT_L1',
		ELOCs.ELOC_BAT_L2:
			'ELOC_BAT_L2',
		ELOCs.ELOC_BAT_LFB1:
			'ELOC_BAT_LFB1',
		ELOCs.ELOC_BAT_LFB2:
			'ELOC_BAT_LFB2',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_1:
			'ELOC_BAT_CHARGING_SWITCH_1',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_2:
			'ELOC_BAT_CHARGING_SWITCH_2',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_3:
			'ELOC_BAT_CHARGING_SWITCH_3',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_4:
			'ELOC_BAT_CHARGING_SWITCH_4',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_5:
			'ELOC_BAT_CHARGING_SWITCH_5',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_6:
			'ELOC_BAT_CHARGING_SWITCH_6',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_7:
			'ELOC_BAT_CHARGING_SWITCH_7',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_8:
			'ELOC_BAT_CHARGING_SWITCH_8',
		ELOCs.ELOC_BAT_CHARGING_SWITCH_9:
			'ELOC_BAT_CHARGING_SWITCH_9',
		ELOCs.ELOC_IR_POW:
			'ELOC_IR_POW',
		ELOCs.ELOC_RADIO_UPLINK:
			'ELOC_RADIO_UPLINK',
		ELOCs.ELOC_RADIO_TRANSMIT:
			'ELOC_RADIO_TRANSMIT',
		ELOCs.ELOC_RADIO_POWER:
			'ELOC_RADIO_POWER',
		ELOCs.ELOC_IMU_INIT:
			'ELOC_IMU_INIT',
		ELOCs.ELOC_IMU_GYRO_INIT:
			'ELOC_IMU_GYRO_INIT',
		ELOCs.ELOC_IMU_ACCEL_INIT:
			'ELOC_IMU_ACCEL_INIT',
		ELOCs.ELOC_IMU_MAG_INIT:
			'ELOC_IMU_MAG_INIT',
		ELOCs.ELOC_SCALING_M:
			'ELOC_SCALING_M',
		ELOCs.ELOC_SCALING_B:
			'ELOC_SCALING_B',
	}[eloc]

def get_ECODE_name(ecode):
	return {
		ECODEs.ECODE_OK:
			'ECODE_OK',
		ECODEs.ECODE_VALID_DATA:
			'ECODE_VALID_DATA',
		ECODEs.ECODE_NO_CHANGE:
			'ECODE_NO_CHANGE',
		ECODEs.ECODE_ABORTED:
			'ECODE_ABORTED',
		ECODEs.ECODE_BUSY:
			'ECODE_BUSY',
		ECODEs.ECODE_SUSPEND:
			'ECODE_SUSPEND',
		ECODEs.ECODE_IO:
			'ECODE_IO',
		ECODEs.ECODE_REQ_FLUSHED:
			'ECODE_REQ_FLUSHED',
		ECODEs.ECODE_TIMEOUT:
			'ECODE_TIMEOUT',
		ECODEs.ECODE_BAD_DATA:
			'ECODE_BAD_DATA',
		ECODEs.ECODE_NOT_FOUND:
			'ECODE_NOT_FOUND',
		ECODEs.ECODE_UNSUPPORTED_DEV:
			'ECODE_UNSUPPORTED_DEV',
		ECODEs.ECODE_NO_MEMORY:
			'ECODE_NO_MEMORY',
		ECODEs.ECODE_INVALID_ARG:
			'ECODE_INVALID_ARG',
		ECODEs.ECODE_BAD_ADDRESS:
			'ECODE_BAD_ADDRESS',
		ECODEs.ECODE_BAD_FORMAT:
			'ECODE_BAD_FORMAT',
		ECODEs.ECODE_BAD_FRQ:
			'ECODE_BAD_FRQ',
		ECODEs.ECODE_DENIED:
			'ECODE_DENIED',
		ECODEs.ECODE_ALREADY_INITIALIZED:
			'ECODE_ALREADY_INITIALIZED',
		ECODEs.ECODE_OVERFLOW:
			'ECODE_OVERFLOW',
		ECODEs.ECODE_NOT_INITIALIZED:
			'ECODE_NOT_INITIALIZED',
		ECODEs.ECODE_SAMPLERATE_UNAVAILABLE:
			'ECODE_SAMPLERATE_UNAVAILABLE',
		ECODEs.ECODE_RESOLUTION_UNAVAILABLE:
			'ECODE_RESOLUTION_UNAVAILABLE',
		ECODEs.ECODE_BAUDRATE_UNAVAILABLE:
			'ECODE_BAUDRATE_UNAVAILABLE',
		ECODEs.ECODE_PACKET_COLLISION:
			'ECODE_PACKET_COLLISION',
		ECODEs.ECODE_PROTOCOL:
			'ECODE_PROTOCOL',
		ECODEs.ECODE_PIN_MUX_INVALID:
			'ECODE_PIN_MUX_INVALID',
		ECODEs.ECODE_READING_HIGH:
			'ECODE_READING_HIGH',
		ECODEs.ECODE_READING_LOW:
			'ECODE_READING_LOW',
		ECODEs.ECODE_OUT_OF_BOUNDS:
			'ECODE_OUT_OF_BOUNDS',
		ECODEs.ECODE_SIGNAL_LOST:
			'ECODE_SIGNAL_LOST',
		ECODEs.ECODE_CONFIRM_TIMEOUT:
			'ECODE_CONFIRM_TIMEOUT',
		ECODEs.ECODE_INCONSISTENT_DATA:
			'ECODE_INCONSISTENT_DATA',
		ECODEs.ECODE_UNEXPECTED_CASE:
			'ECODE_UNEXPECTED_CASE',
		ECODEs.ECODE_WATCHDOG_EARLY_WARNING:
			'ECODE_WATCHDOG_EARLY_WARNING',
		ECODEs.ECODE_WATCHDOG_RESET:
			'ECODE_WATCHDOG_RESET',
		ECODEs.ECODE_WATCHDOG_DID_KICK:
			'ECODE_WATCHDOG_DID_KICK',
		ECODEs.ECODE_EXCESSIVE_SUSPENSION:
			'ECODE_EXCESSIVE_SUSPENSION',
		ECODEs.ECODE_CRIT_ACTION_MUTEX_TIMEOUT:
			'ECODE_CRIT_ACTION_MUTEX_TIMEOUT',
		ECODEs.ECODE_I2C_IRPOW_MUTEX_TIMEOUT:
			'ECODE_I2C_IRPOW_MUTEX_TIMEOUT',
		ECODEs.ECODE_PROC_ADC_MUTEX_TIMEOUT:
			'ECODE_PROC_ADC_MUTEX_TIMEOUT',
		ECODEs.ECODE_HW_STATE_MUTEX_TIMEOUT:
			'ECODE_HW_STATE_MUTEX_TIMEOUT',
		ECODEs.ECODE_USART_MUTEX_TIMEOUT:
			'ECODE_USART_MUTEX_TIMEOUT',
		ECODEs.ECODE_SPI_MUTEX_TIMEOUT:
			'ECODE_SPI_MUTEX_TIMEOUT',
		ECODEs.ECODE_BAT_CHARGING_MUTEX_TIMEOUT:
			'ECODE_BAT_CHARGING_MUTEX_TIMEOUT',
		ECODEs.ECODE_WATCHDOG_MUTEX_TIMEOUT:
			'ECODE_WATCHDOG_MUTEX_TIMEOUT',
		ECODEs.ECODE_EQUISTACK_MUTEX_TIMEOUT:
			'ECODE_EQUISTACK_MUTEX_TIMEOUT',
		ECODEs.ECODE_ALL_MUTEX_TIMEOUT:
			'ECODE_ALL_MUTEX_TIMEOUT',
		ECODEs.ECODE_REWROTE_PROG_MEM:
			'ECODE_REWROTE_PROG_MEM',
		ECODEs.ECODE_STACK_OVERFLOW:
			'ECODE_STACK_OVERFLOW',
		ECODEs.ECODE_DET_ALREADY_HIGH:
			'ECODE_DET_ALREADY_HIGH',
		ECODEs.ECODE_BAT_NOT_DISCHARGING:
			'ECODE_BAT_NOT_DISCHARGING',
		ECODEs.ECODE_BAT_NOT_NOT_DISCHARGING:
			'ECODE_BAT_NOT_NOT_DISCHARGING',
		ECODEs.ECODE_BAT_NOT_CHARGING:
			'ECODE_BAT_NOT_CHARGING',
		ECODEs.ECODE_BAT_NOT_NOT_CHARGING:
			'ECODE_BAT_NOT_NOT_CHARGING',
		ECODEs.ECODE_BAT_NOT_DISCHARGING_RESTART:
			'ECODE_BAT_NOT_DISCHARGING_RESTART',
		ECODEs.ECODE_BAT_FAULT:
			'ECODE_BAT_FAULT',
		ECODEs.ECODE_BAT_NOT_FULL_FOR_WHILE:
			'ECODE_BAT_NOT_FULL_FOR_WHILE',
		ECODEs.ECODE_BAT_LOW_VOLTAGE_FOR_WHILE:
			'ECODE_BAT_LOW_VOLTAGE_FOR_WHILE',
		ECODEs.ECODE_RECOMMISSION:
			'ECODE_RECOMMISSION',
		ECODEs.ECODE_ALL_SAME_VAL:
			'ECODE_ALL_SAME_VAL',
		ECODEs.ECODE_CORRUPTED:
			'ECODE_CORRUPTED',
		ECODEs.ECODE_CORRUPTED_FATAL:
			'ECODE_CORRUPTED_FATAL',
		ECODEs.ECODE_INVALID_STATE_CHANGE:
			'ECODE_INVALID_STATE_CHANGE',
		ECODEs.ECODE_TIMESTAMP_WRAPAROUND:
			'ECODE_TIMESTAMP_WRAPAROUND',
		ECODEs.ECODE_INCONSISTENT_STATE:
			'ECODE_INCONSISTENT_STATE',
		ECODEs.ECODE_PWM_CUR_LOW_ON_DEPLOY:
			'ECODE_PWM_CUR_LOW_ON_DEPLOY',
		ECODEs.ECODE_PWM_CUR_LOW_ON_MAX_CYCLE:
			'ECODE_PWM_CUR_LOW_ON_MAX_CYCLE',
		ECODEs.ECODE_PWM_CUR_VERY_LOW_ON_DEPLOY:
			'ECODE_PWM_CUR_VERY_LOW_ON_DEPLOY',
		ECODEs.ECODE_PWM_CUR_VERY_LOW_ON_MAX_CYCLE:
			'ECODE_PWM_CUR_VERY_LOW_ON_MAX_CYCLE',
		ECODEs.ECODE_SOFTWARE_RESET:
			'ECODE_SOFTWARE_RESET',
		ECODEs.ECODE_SAT_RESET:
			'ECODE_SAT_RESET',
		ECODEs.ECODE_BAT_LI_TIMEOUT:
			'ECODE_BAT_LI_TIMEOUT',
		ECODEs.ECODE_BAT_LF_TIMEOUT:
			'ECODE_BAT_LF_TIMEOUT',
		ECODEs.ECODE_IR_POW_IN_USE_ON_STATE_CHANGE:
			'ECODE_IR_POW_IN_USE_ON_STATE_CHANGE',
		ECODEs.ECODE_UPLINK_REBOOT:
			'ECODE_UPLINK_REBOOT',
		ECODEs.ECODE_UPLINK_KILL3DAYS:
			'ECODE_UPLINK_KILL3DAYS',
		ECODEs.ECODE_UPLINK_KILL1WEEK:
			'ECODE_UPLINK_KILL1WEEK',
		ECODEs.ECODE_UPLINK_KILLFOREVER:
			'ECODE_UPLINK_KILLFOREVER',
		ECODEs.ECODE_UPLINK_REVIVED:
			'ECODE_UPLINK_REVIVED',
		ECODEs.ECODE_P1_NOT_DEPLOYED:
			'ECODE_P1_NOT_DEPLOYED',
		ECODEs.ECODE_P2_NOT_DEPLOYED:
			'ECODE_P2_NOT_DEPLOYED',
		ECODEs.ECODE_P3_NOT_DEPLOYED:
			'ECODE_P3_NOT_DEPLOYED',
		ECODEs.ECODE_IRPOW_SEM_TOO_MANY_USERS:
			'ECODE_IRPOW_SEM_TOO_MANY_USERS',
		ECODEs.ECODE_IRPOW_SEM_TOO_FEW_USERS:
			'ECODE_IRPOW_SEM_TOO_FEW_USERS',
		ECODEs.ECODE_I2C_BUS_ERROR:
			'ECODE_I2C_BUS_ERROR',
		ECODEs.ECODE_BAT_LF_CELLS_UNBALANCED:
			'ECODE_BAT_LF_CELLS_UNBALANCED',
		ECODEs.ECODE_VALID_STATE_CHANGE:
			'ECODE_VALID_STATE_CHANGE',
	}[ecode]